name: Docker-node-ec2-CI
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      fontend: ${{steps.deploy-conditions.outputs.frontend}}
      backend: ${{steps.deploy-conditions.outputs.backend}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: ssh-ing
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          GIT_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER_NAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: deploy-conditions
        run: |
          ls -a
          cat >> difference.sh <<END
            frontend=0
            backend=0
            git diff --name-only HEAD^ HEAD >> diff.txt
            if grep -q "frontend" diff.txt; then
              echo "changes present in frontend"
              frontend=1
            fi
            if grep -q "backend" diff.txt; then
              echo "Changes present in backend"
              backend=1
            fi
            echo "BACKEND=$backend" >> $GITHUB_ENV
            echo "FRONTEND=$frontend" >> $GITHUB_ENV
          END
          chmod +x difference.sh
          ./difference.sh
          cat diff.txt

      - name: env-file-transfer
        run: |
          echo $ENV > .env
          scp .env staging:ecommerce/backend/.env
        env:
          ENV: ${{secrets.BACKEND_ENV}}
      - name: stop-docker-frontend
        if: ${{ vars.FRONTEND == 1 }}
        continue-on-error: true
        run: ssh staging 'docker stop ec2-docker-react && docker rm ec2-docker-react'
      - name: stop-docker-backend
        if: ${{ vars.BACKEND == 1 }}
        continue-on-error: true
        run: ssh staging 'docker stop ec2-docker-nest && docker rm ec2-docker-nest'
      - name: clone-repo
        run: |
          echo ${{vars.FRONTEND}}
          echo ${{vars.BACKEND}}
          ssh staging '
            cd ~/ecommerce &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main       
          '

      - name: docker-build-deploy-frontend
        if: ${{ vars.FRONTEND == 1 }}
        run: >
          echo "Frontend Deploying..."

          ssh staging '
            cd ~/ecommerce/frontend &&
            docker build -t ec2-docker-react . &&
            docker run --name ec2-docker-react -d -p 3007:3007 --add-host=host.docker.internal:host-gateway ec2-docker-react:latest       
          '
      - name: docker-build-deploy-backend
        if: ${{ vars.BACKEND == 1 }}
        run: >
          echo "Backend Deploying..."

          ssh staging '
            cd ~/ecommerce/backend &&
            docker build -t ec2-docker-nest . &&
            docker run --name ec2-docker-nest -d -p 3008:3008 --add-host=host.docker.internal:host-gateway ec2-docker-nest:latest
          '
